import { generateText } from "ai";
import { MockLanguageModelV4 } from "ai/test";
import { describe, expect, it } from "vitest";
import { createRouter } from "../router";
import { asV4, finishReason, genOptions, okModel, usage } from "./test-kit";

describe("createRouter — fallback", () => {
  it("consumes rejected nested generated file payloads before fallback", async () => {
    const primary = new MockLanguageModelV4({
      doGenerate: async () =>
        ({
          content: [
            {
              data: {
                data: Promise.reject(new Error("async generated file data")),
                type: "data",
              },
              mediaType: "image/png",
              type: "file",
            },
            {
              mediaType: Promise.reject(
                new Error("async generated media type sibling")
              ),
              providerMetadata: Promise.reject(
                new Error("async generated metadata sibling")
              ),
              type: Promise.reject(
                new Error("async generated content discriminant")
              ),
            },
          ],
          finishReason,
          usage,
          warnings: [],
        }) as never,
    });
    const route = createRouter({
      models: { chat: [primary, okModel("file fallback")] },
    });

    await expect(
      generateText({ model: route("chat"), prompt: "hi" })
    ).resolves.toMatchObject({ text: "file fallback" });
    await new Promise((resolve) => setTimeout(resolve, 0));
  });

  it("snapshots mutable generated byte and URL payloads", async () => {
    const bytes = new Uint8Array([1, 2, 3]);
    const url = new URL("https://example.com/file.png");
    const primary = new MockLanguageModelV4({
      doGenerate: () =>
        Promise.resolve({
          content: [
            {
              data: { data: bytes, type: "data" },
              mediaType: "image/png",
              type: "file",
            },
            {
              data: { type: "url", url },
              mediaType: "image/png",
              type: "file",
            },
          ],
          finishReason,
          usage,
          warnings: [],
        } as never),
    });
    const route = createRouter({ models: { chat: [primary] } });

    const result = await asV4(route("chat")).doGenerate(genOptions);
    const bytePart = result.content[0] as { data: { data: Uint8Array } };
    const urlPart = result.content[1] as { data: { url: URL } };
    bytes[0] = 9;
    url.pathname = "/mutated.png";

    expect(bytePart.data.data).not.toBe(bytes);
    expect([...bytePart.data.data]).toEqual([1, 2, 3]);
    expect(urlPart.data.url).not.toBe(url);
    expect(urlPart.data.url.toString()).toBe("https://example.com/file.png");
  });
});
